osx_image: xcode7.1
language: objective-c
cache:
  directories:
  - node_modules/
  - SlackerReferenceApp/node_modules
  - /usr/local/lib/node_modules/cordova
  - /usr/local/lib/node_modules/bower

global:
before_install:
- echo "Before install stage"
- sudo easy_install cpp-coveralls
- brew update
- brew upgrade node
- brew install gcovr
- node -v
- echo "END - Before install stage"
install:
- echo "Install stage"
- sudo npm install -g bower
- sudo npm install -g cordova
- echo "END - install stage"
before_script:
- echo "Before script stage"
- fastlane cordova
script:
- echo "Starting build"
- fastlane build
after_success:
- echo "Build success"
- fastlane deploy
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
