osx_image: xcode7.1
language: objective-c
cache:
  directories:
    - node_modules/
    - SlackerReferenceApp/node_modules
    - /usr/local/lib/node_modules/ionic
    - /usr/local/lib/node_modules/cordova
    - /usr/local/lib/node_modules/ios-sim
    - /usr/local/lib/node_modules/bower

#addons:
#  sauce_connect: true

global:
before_install:
# Commands to excecute before install
  - echo "Before install stage"
  - sudo easy_install cpp-coveralls
  - brew update
  - brew upgrade node
  - brew install gcovr
  - node -v
  - echo "END - Before install stage"

install:
  - echo "Install stage"
#  - npm i
  - sudo npm install -g bower
  - sudo npm install -g cordova
  - sudo npm install -g ionic
  #- sudo npm install -g ios-deploy
  - sudo npm install -g ios-sim
  - echo "END - install stage"

before_script:
# Commands to excecute before running tests
  - echo "Before script stage"
  - fastlane ionic

script:
# Run tests
#  - echo "Running tests"
#  - npm test
  - echo "Starting build"
  - fastlane build
#  - cd TestCIiOS
#  - cordova build ios

after_success:
# You can do thing after success
  - echo "Build success"
  - fastlane deploy

after_failure:
# What if your test fails?
  - echo "After failure stage"

after_script:
# Do things anyway after script/test pass or not
  - echo "After script stage"
#  notifications:
#  slack:
#    rooms:
#      - agilesoftwaredev:${SLACK_BOT_TOKEN}#internationalmixmob
