# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.47.0"

default_platform :ios


platform :ios do
  before_all do
#    scan(
#        project: "SlackerReferenceApp/platforms/ios/SlackerReferenceApp.xcodeproj",
#        scheme: "SlackerReferenceApp",
#        device: "iPhone 6",
#        clean: true,
#        code_coverage: true,
#        output_directory: "SlackerReferenceApp/platforms/ios/build",
#        slack_url: ENV["SLACK_URL"],
#        slack_channel: "internationalmixmob"
#    )
  end

  desc "Run Cordova Cmds"
  lane :cordova do
    sh "cd ../SlackerReferenceApp ; cordova prepare --variable SLACK_CLIENT_ID='" + ENV['SLACK_CLIENT_ID'] + "' --variable SLACK_CLIENT_SECRET='" + ENV['SLACK_CLIENT_SECRET'] + "' "
    #sh "cd ../SlackerReferenceApp ; cordova build ios --variable SLACK_CLIENT_ID='" + ENV['SLACK_CLIENT_ID'] + "' --variable SLACK_CLIENT_SECRET='" + ENV['SLACK_CLIENT_SECRET'] + "' "
  end

  desc "Run Ionic Cmds"
  lane :ionic do
    sh "cd ../SlackerReferenceApp ; ionic prepare --variable SLACK_CLIENT_ID='" + ENV['SLACK_CLIENT_ID'] + "' --variable SLACK_CLIENT_SECRET='" + ENV['SLACK_CLIENT_SECRET'] + "' "
    #sh "cd ../SlackerReferenceApp ; ionic build ios --variable SLACK_CLIENT_ID='" + ENV['SLACK_CLIENT_ID'] + "' --variable SLACK_CLIENT_SECRET='" + ENV['SLACK_CLIENT_SECRET'] + "' "
  end

  desc "Runs all the tests"
  lane :test do
#    xctool :test, [
#      "--project", "'./SlackerReferenceApp/platforms/ios/SlackerReferenceApp.xcodeproj'",
#    #  "--scheme", "'SlackerReferenceApp'",
#      "--configuration", "Debug",
#      "--sdk", "iphonesimulator",
#      "--arch", "i386",
#      "OBJROOT=./SlackerReferenceApp/platforms/ios/build",
#      "ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES"
#    ].join(" ")

  end

  desc "Create a Build"
  desc "This will also make sure the profile is up to date"
  lane :build do
    increment_build_number (
      xcodeproj: "SlackerReferenceApp/platforms/ios/SlackerReferenceApp.xcodeproj"
    )
    cert
    sigh(
      adhoc: true
    )
    gym(
      project: "SlackerReferenceApp/platforms/ios/SlackerReferenceApp.xcodeproj",
      scheme: "SlackerReferenceApp",
      output_directory: "SlackerReferenceApp/platforms/ios/build",
      output_name: "SlackerDemo.ipa",
      use_legacy_build_api: true
    ) # Build your app - more options available

  end

  desc "Deploy a new version to HockeyApp"
  lane :deploy do
    hockey(
      api_token: ENV['HOCKEY_API_TOKEN'],
      ipa: './SlackerReferenceApp/platforms/ios/build/SlackerDemo.ipa',
      notes: "Changelog"
    )
    slack(
      slack_url: ENV["SLACK_URL"],
      message: "Successfully deployed new App Update. Public Download URL " + lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK]
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
